services:
  quizapp:
    build: .
    image: ghcr.io/rutra8002/quizapp:master
    environment:
      FLASK_ENV: production
      SECRET_KEY: ${SECRET_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    volumes:
      - ./instance:/app/instance
    restart: unless-stopped

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - quizapp
    restart: unless-stopped

volumes:
  caddy_data: {}
  caddy_config: {}